<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Report1.rdlc" />
    <None Remove="Report2.rdlc" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Report1.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Report2.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="DataSet\dsEmployee.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsEmployee.xsd</DependentUpon>
    </Compile>
    <Compile Update="DataSet\dsReport3.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsReport3.xsd</DependentUpon>
    </Compile>
    <Compile Update="DataSet\dsSalary.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsSalary.xsd</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="ReportMaking\dsGoodsDeliveryReport.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsGoodsDeliveryReport.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="DataSet\dsEmployee.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsEmployee.Designer.cs</LastGenOutput>
    </None>
    <None Update="DataSet\dsReport3.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsReport3.Designer.cs</LastGenOutput>
    </None>
    <None Update="DataSet\dsSalary.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsSalary.Designer.cs</LastGenOutput>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="ReportMaking\dsGoodsDeliveryReport.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsGoodsDeliveryReport.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>