<Project Sdk="Microsoft.NET.Sdk.Web">

  <!-- ================= BASIC ================= -->
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>


  <!-- ================= PROJECT REFERENCES ================= -->
  <ItemGroup>
    <ProjectReference Include="..\Erp.Application\Erp.Application.csproj" />
    <ProjectReference Include="..\Erp.Infrastructure\Erp.Infrastructure.csproj" />
    <ProjectReference Include="..\RDLCProject\RDLCProject.csproj" />
  </ItemGroup>


  <!-- ================= NUGET PACKAGES ================= -->
  <ItemGroup>
    <PackageReference Include="Microsoft.ReportingServices.ReportViewerControl.WebForms" Version="150.1652.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.10" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
    <PackageReference Include="AspNetCore.Reporting" Version="2.1.0" />
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="IronXL.Excel" Version="2022.11.10251" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.16" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NSwag.AspNetCore" Version="13.19.0" />
    <PackageReference Include="NSwag.MSBuild" Version="13.19.0" PrivateAssets="all" />
    <PackageReference Include="Select.HtmlToPdf.NetCore" Version="22.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="7.0.6" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
  </ItemGroup>


  <!-- ================= DATASET AUTO GENERATION ================= -->
  <ItemGroup>
    <!-- Auto create all Designer.cs from XSD -->
    <None Update="wwwroot\DataSet\**\*.xsd">
      <SubType>Designer</SubType>
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>%(Filename).Designer.cs</LastGenOutput>
    </None>

    <!-- Copy all RDLC reports -->
    <None Update="wwwroot\Reports\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>


  <!-- ================= FOLDERS ================= -->
  <ItemGroup>
    <Folder Include="Validators\" />
    <Folder Include="wwwroot\Files\" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="wwwroot\DataSet\dsDateWiseHourlyQCReportSummary.Designer.cs">
      <DependentUpon>dsDateWiseHourlyQCReportSummary.xsd</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Content>
    <Content Update="wwwroot\DataSet\dsDateWiseHourlyQCReportSummary.xsd">
      <LastGenOutput>dsDateWiseHourlyQCReportSummary.Designer.cs</LastGenOutput>
      <Generator>MSDataSetGenerator</Generator>
    </Content>
    <Content Update="wwwroot\DataSet\dsDateWiseHourlyQCReport.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsDateWiseHourlyQCReport.xsd</DependentUpon>
    </Content>
    <Content Update="wwwroot\DataSet\dsDateWiseHourlyQCReport.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsDateWiseHourlyQCReport.Designer.cs</LastGenOutput>
    </Content>
  </ItemGroup>

</Project>
